# -*- coding: utf-8 -*-
"""Полировка UI после QA (2026-06-22). Точечные правки строк перевода.
Игра может быть запущена: ручные .txt подхватятся по ALT+R; _AutoGen может потребовать рестарт."""
import io, os

ROOT = r"C:\Users\User\Downloads\gunsaw-demo-win\BepInEx\Translation\ru\Text"
def read(p): return io.open(p, encoding="utf-8").read()
def write(p, s): io.open(p, "w", encoding="utf-8", newline="\n").write(s)

# ---- (A) уникальные точечные замены (assert ровно 1 совпадение) ----
A = {
 "ui_settings.txt": [
   ("Tinnitus volume=Громкость звона в ушах", "Tinnitus volume=Громкость тиннитуса"),
   # видео: названия опций обратно на английский (тултипы-описания остаются на русском)
   ("Windowed/Borderless=Оконный/Без рамки", "Windowed/Borderless=Windowed/Borderless"),
   ("Desaturation=Обесцвечивание", "Desaturation=Desaturation"),
   ("Underwater blur=Подводное размытие", "Underwater blur=Underwater blur"),
   ("Bloom=Свечение", "Bloom=Bloom"),
   ("Film grain=Зернистость", "Film grain=Film grain"),
   ("Tonemapping=Тонмаппинг", "Tonemapping=Tonemapping"),
   ("Simple weather=Простая погода", "Simple weather=Simple weather"),
   ("Simple lighting=Простое освещение", "Simple lighting=Simple lighting"),
   ("Splatter amount=Количество брызг", "Splatter amount=Splatter amount"),
   ("V-Sync=Вертикальная синхронизация", "V-Sync=V-Sync"),
   ("Interpolation=Интерполяция", "Interpolation=Interpolation"),
   # бинды — укорот
   ("Walk/drop/spit=Ходьба/сброс/плевок", "Walk/drop/spit=Шаг/сброс/плевок"),
   ("Toggle UI=Переключить интерфейс", "Toggle UI=Интерфейс"),
   ("Toggle timer=Переключить таймер", "Toggle timer=Таймер"),
   ("Pick up weapon=Подобрать оружие", "Pick up weapon=Взять оружие"),
   ("Reset to defaults=Сбросить по умолчанию", "Reset to defaults=Сбросить"),
 ],
 "_test_menu.txt": [
   ("BACK TO TITLE=В ГЛАВНОЕ МЕНЮ", "BACK TO TITLE=В МЕНЮ"),
   ("Starting weapon:=Начальное оружие:", "Starting weapon:=Стартовое оружие:"),
 ],
 "ui_game.txt": [
   ("Hue=Оттенок", "Hue=Тон"),
   ("Saturation=Насыщенность", "Saturation=Насыщ."),
   ("Back to\\nmain menu=Назад в\\nглавное меню", "Back to\\nmain menu=В меню"),
 ],
}
for fn, reps in A.items():
    p = os.path.join(ROOT, fn); s = read(p)
    for old, new in reps:
        n = s.count(old)
        assert n == 1, "НЕ 1 совпадение: %s | %r | found=%d" % (fn, old, n)
        s = s.replace(old, new)
    write(p, s); print("OK (A)", fn, "->", len(reps), "правок")

# ---- (B) укорот статов в меню выбора, только по англ-ключу ----
STAT_KEY = ("Aim speed", "Reload speed", "Move speed")
VAL = [("Скорость прицеливания","Прицел"), ("Скорость перезарядки","Перезарядка"),
       ("Скорость передвижения","Движение"), ("Скорость движения","Движение")]
def shorten(line):
    if "=" not in line: return line, 0
    k, v = line.split("=", 1)
    if not k.startswith(STAT_KEY): return line, 0
    n = 0
    for a, b in VAL:
        if a in v: v = v.replace(a, b); n += 1
    return k + "=" + v, n
for fn in ("ui_game.txt", "_AutoGeneratedTranslations.txt"):
    p = os.path.join(ROOT, fn); lines = read(p).split("\n"); cnt = 0; out = []
    for ln in lines:
        nl, n = shorten(ln); out.append(nl); cnt += n
    write(p, "\n".join(out)); print("OK (B) статы", fn, "->", cnt, "замен")
# regex в ui_fixes
p = os.path.join(ROOT, "ui_fixes.txt"); s = read(p)
for old, new in [
   ('r:"^Aim\\s+speed:\\s*(.+)$"=Скорость прицеливания: $1', 'r:"^Aim\\s+speed:\\s*(.+)$"=Прицел: $1'),
   ('r:"^Reload\\s+speed:\\s*(.+)$"=Скорость перезарядки: $1', 'r:"^Reload\\s+speed:\\s*(.+)$"=Перезарядка: $1'),
   ('r:"^Move\\s+speed:\\s*(.+)$"=Скорость передвижения: $1', 'r:"^Move\\s+speed:\\s*(.+)$"=Движение: $1'),
]:
    assert s.count(old) == 1, "ui_fixes regex не найден: %r" % old
    s = s.replace(old, new)
write(p, s); print("OK (B) ui_fixes regex")

# ---- (C) Дюн: укорот хвоста описания (в ui_game + кэш если есть) ----
DUNE_OLD = "Высокий уровень мастерства ; высокий уровень угрозы.\\nНе относись легкомысленно."
DUNE_NEW = "Высокий навык, высокая угроза.\\nНе расслабляйся."
for fn in ("ui_game.txt", "_AutoGeneratedTranslations.txt"):
    p = os.path.join(ROOT, fn); s = read(p); c = s.count(DUNE_OLD)
    if c: s = s.replace(DUNE_OLD, DUNE_NEW); write(p, s)
    print("OK (C) Дюн-хвост", fn, "->", c)
print("ГОТОВО")
