# -*- coding: utf-8 -*-
"""Видимые строки дампа, не покрытые ни одним переводом (плейн-ключ ИЛИ англ.ключ из JSON воркфлоу)."""
import io, glob, json, re, os
ROOT="."
TEXTDIR="BepInEx/Translation/ru/Text"
VIS={"MainMenuManager","BodyScript","MissionSelect","WeaponPreset","SceneLoader~raw",
     "GameManager~raw","EnemyWeaponChanger","TMPro.TextMeshProUGUI","TMPro.TextMeshPro"}

# 1) covered: плейн-ключи всех файлов + англ.ключи из всех JSON-выходов воркфлоу
covered=set()
for fp in glob.glob(os.path.join(TEXTDIR,"*.txt")):
    if os.path.basename(fp) in ("_Substitutions.txt","_Preprocessors.txt","_Postprocessors.txt","_AutoGeneratedTranslations.txt"): continue
    for ln in io.open(fp,encoding="utf-8"):
        s=ln.rstrip("\n")
        if not s or s.startswith(("//","r:","sr:")) or "=" not in s: continue
        covered.add(s.split("=",1)[0])
for fp in glob.glob("docs/wf_out/out_*.json")+glob.glob("docs/wf_editor_out/out_*.json"):
    try:
        for r in json.load(io.open(fp,encoding="utf-8")):
            if r.get("ru"): covered.add(r.get("key",""))
    except Exception: pass

def junk(s):
    if "=" in s and not s.startswith("r:"): pass
    if len(s)<3: return True
    if "/" in s and " " not in s: return True          # пути/ID
    if re.fullmatch(r'[a-z0-9_]+', s): return True       # внутр. ID (base/chik/g4a)
    if re.fullmatch(r'[A-Za-z0-9 ._-]+', s) and " " not in s and s[:1].isupper() and len(s)<14:
        return True                                      # модели/одно слово (AK47) — отдельно
    return False

gaps=[]
seen=set()
for ln in io.open("docs/strings_assets.txt",encoding="utf-8"):
    s=ln.rstrip("\n")
    if "\t" not in s: continue
    val,tag=s.rsplit("\t",1)
    comps=set(tag.strip("[]").split(","))
    if not (comps & VIS): continue
    if val in covered or val in seen: continue
    seen.add(val)
    gaps.append((val,tag))

# раздели на «фразы» (длинные/с пробелами) и «токены» (модели оружия и пр.)
phrases=[(v,t) for v,t in gaps if (" " in v and len(v)>=10) or "\n" in v]
tokens=[(v,t) for v,t in gaps if not ((" " in v and len(v)>=10) or "\n" in v)]
print("ВИДИМЫХ НЕПОКРЫТЫХ всего:",len(gaps),"| фраз:",len(phrases),"| токенов:",len(tokens))
io.open("docs/visible_gaps.txt","w",encoding="utf-8").write(
    "## ФРАЗЫ (нужен перевод)\n"+"\n".join(f"{v}\t{t}" for v,t in phrases)+
    "\n\n## ТОКЕНЫ (модели/одно слово — решить транслит/оставить)\n"+"\n".join(f"{v}\t{t}" for v,t in tokens)+"\n")
print("\n--- ФРАЗЫ (first 60) ---")
for v,t in phrases[:60]: print(f"[{t}] {v[:100]}")
print("\n--- ТОКЕНЫ (first 50) ---")
print(", ".join(v for v,_ in tokens[:50]))
