# -*- coding: utf-8 -*-
"""Фикс наведения на оружие: mouseOverText = stats.name + ", " + ammo + " rounds" (декомпил 15482).
Старый generic-regex r:"^(.+?),\s+(\d+)\s+rounds$"=$1,$2 прогонял ИМЯ оружия насквозь по-английски
(XUnity не переводит захваченную группу). Заменяем на per-weapon regex по реальному набору из 37
WeaponPreset.name (tools/dump_weapon_names.py), переиспользуя уже существующий перевод имени.
Плюс чистим авто-кэш XUnity от плохих закэшированных строк (иначе точный кэш перекрыл бы regex)."""
import io, os, re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEXTDIR = os.path.join(ROOT, "BepInEx", "Translation", "ru", "Text")
FIXES = os.path.join(TEXTDIR, "ui_fixes.txt")
CACHE = os.path.join(TEXTDIR, "_AutoGeneratedTranslations.txt")

# 37 отображаемых имён (WeaponPreset.name) -> русский (значения = уже существующие плейн-ключи).
# PDW→ПОС (персональное оружие самообороны), Stench Gun→Газомёт — по запросу. Vitya/PDW — добор.
W = [
    ("Assault rifle", "Штурмовая винтовка"),
    ("Bullpup rifle", "Винтовка булл-пап"),
    ("Full-auto shotgun", "Автоматический дробовик"),
    ("Grenade Launcher", "Гранатомёт"),
    ("Heavy Rifle", "Тяжёлая винтовка"),
    ("Light pistol", "Лёгкий пистолет"),
    ("Machine pistol", "Автоматический пистолет"),
    ("Makeshift rifle", "Самодельная винтовка"),
    ("Marksman rifle", "Марксманская винтовка"),
    ("Mini SMG", "Мини-ПП"),
    ("Old rifle", "Старая винтовка"),
    ("Rapid-fire revolver", "Скорострельный револьвер"),
    ("Rectangle Gun", "Прямоугольная пушка"),
    ("Rocket Launcher", "Ракетомёт"),
    ("Sawed Off", "Обрез"),
    ("Semi-auto shotgun", "Полуавтоматический дробовик"),
    ("Sniper rifle", "Снайперская винтовка"),
    ("Spec-ops rifle", "Винтовка спецназа"),
    ("Stench Gun", "Газомёт"),
    ("Tactical rifle", "Тактическая винтовка"),
    ("Tactical SMG", "Тактический ПП"),
    ("Trench Sweeper", "Окопная метла"),
    ("go away", "уйди"),
    ("Carbine", "Карабин"),
    ("Derringer", "Дерринджер"),
    ("Garand", "Гаранд"),
    ("Governor", "Губернатор"),
    ("Magnum", "Магнум"),
    ("Operator", "Оператор"),
    ("Papasha", "Папаша"),
    ("PDW", "ПОС"),
    ("Pistol", "Пистолет"),
    ("Prototype", "Прототип"),
    ("Revolver", "Револьвер"),
    ("SMG", "ПП"),
    ("Unarmed", "Без оружия"),
    ("Vitya", "Витя"),
]
assert len(W) == 37, len(W)

def name_re(eng):
    # пробелы -> \s+ (нормализация XUnity); токены экранируем
    return r'\s+'.join(re.escape(tok) for tok in eng.split())

# --- блок для ui_fixes ---
lines = [
    "// === Наведение на оружие: stats.name + \", \" + ammoAmount + \" rounds\" (декомпил 15482). ===",
    "// 37 реальных WeaponPreset.name (tools/dump_weapon_names.py). Per-weapon regex — иначе имя",
    "// проходит в $1 по-английски. Значение имени = соответствующий плейн-ключ (HUD оружия).",
    "// Добор недостающих плейн-ключей (HUD): Vitya. PDW→ПОС.",
    "Vitya=Витя",
]
for eng, ru in W:
    lines.append('r:"^%s,\\s+(\\d+)\\s+rounds$"=%s, $1 патр.' % (name_re(eng), ru))
block = "\n".join(lines)

# --- вставка в ui_fixes: заменяем старый generic-regex (+ его комментарий) ---
src = io.open(FIXES, encoding="utf-8").read()
old_comment = "// мышь-овер по оружию: stats.name + \", \" + N + \" rounds\" (имя остаётся как есть)\n"
old_regex = 'r:"^(.+?),\\s+(\\d+)\\s+rounds$"=$1, $2 патр.\n'
assert old_regex in src, "generic-regex не найден в ui_fixes"
src = src.replace(old_comment + old_regex, block + "\n")
io.open(FIXES, "w", encoding="utf-8", newline="\n").write(src)
print("ui_fixes.txt: generic-regex -> %d per-weapon regex + Vitya плейн-ключ" % len(W))

# --- чистка авто-кэша от плохих строк наведения ---
removed = 0
if os.path.exists(CACHE):
    keep = []
    for ln in io.open(CACHE, encoding="utf-8"):
        if re.search(r',\s+\d+\s+rounds=', ln):   # любая закэшированная строка "<имя>, N rounds=..."
            removed += 1
            continue
        keep.append(ln)
    io.open(CACHE, "w", encoding="utf-8", newline="\n").write("".join(keep))
print("_AutoGeneratedTranslations.txt: удалено плохих кэш-строк наведения =", removed)
